# Generated by Django 5.2.7 on 2025-10-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('kathmandu', 'kathmandu'), ('Pokhara', 'Pokhara'), ('Dolakha', 'Dolakha'), ('Bhaktapur', 'Bhaktapur'), ('Nepal', 'Nepal'), ('Bhaktapur', 'Bhaktapur'), ('Gorkha', 'Gorkha'), ('Dolpa', 'Dolpa'), ('Rolpa', 'Rolpa'), ('Jhapa', 'Jhapa')], max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
